### ISSUE TITLE
dotnet/python: Respect JSII_RUNTIME and JSII_DEBUG

### ISSUE THREAD

**Issue by eladb** [awslabs/jsii#245]
The .NET and python jsii runtime clients should respect `JSII_RUNTIME` and `JSII_DEBUG`:

* If `JSII_RUNTIME` is non-empty, it will be interpreted as a path to a `jsii-runtime` program, instead of the built-in one.
* If `JSII_DEBUG` is non-empty, it will be propagated to the child runtime _and_ STDERR output from the child process will be printed to STDERR of the parent process. Any debug output from the jsii runtime client should also be emitted to stderr in this case.

Copy: @dstufft (for python), @costleya (for .NET)

**Comment by fulghum** [comment]
@dstufft and @garnaat – I know I asked about this (and got an answer) last week and we are setting JSII_RUNTIME, but wanted to double-check before I close this (or remove the python tag and followed up with .NET).  Let me know if there're more work here, otherwise I'm assuming we've completed it for Python.

**Comment by dstufft** [comment]
No that's not right, we're setting ``JSII_AGENT`` and we respect ``JSII_DEBUG``. Unless @garnaat has added it we still don't respect ``JSII_RUNTIME``.

**Comment by garnaat** [comment]
I have not added anything to support `JSII_RUNTIME`. I can look at adding that.

**Comment by fulghum** [comment]
ah... glad I double-checked. :-) thanks for the extra info here.
