### ISSUE TITLE
Java varargs for list syntax

### ISSUE THREAD

**Issue by fulghum** [awslabs/jsii#276]
More use of varargs would help simplify the Java coding experience when passing in a list of items.  For example, not having to use Collections.singletonList would make the code less verbose and more readable.

**Comment by eladb** [comment]
This works as intended (see [conformance test]()). jsii supports variadic arguments, which will be represented as variadic arguments in Java. If the class author chooses to represent an argument as an array instead of variadic arguments, this will be the Java representation. It doesn't make sense to special-case arrays for Java, because this cause loss of fidelity from the author's intent.
