### ISSUE TITLE
Move the "optional" attribute from TypeReference to Parameter

### ISSUE THREAD

**Issue by RomainMuller** [awslabs/jsii#296]
The specification models the `optional` attribute of parameters on their `TypeReference` instead of directly on the parameter. This creates a confusion between `null`able and `optional`.

The specification needs to be modified so optional parameters carry an `optional` attribute, while `TypeReferences` carry a `nullable` attribute.

Related: #230 #284 #295

**Comment by rix0rrr** [comment]
So I wanted a function like such:

```ts
method(anchor: Construct | undefined, realParameter: string, optionalParameter?: string) {
}
```

Because that method order made most sense (and yet we didn't necessarily have the first argument always available), but this was rejected.

I've had to reorder arguments, which is not a BIG deal but it was suboptimal to my mind.

**Comment by eladb** [comment]
@rix0rrr I think is a different issue than where we model optionality of parameters. This is basically about nullibility of parameters, which is currently not supported by jsii (and should in my mind). Care to raise a separate issue?

**Comment by rix0rrr** [comment]
It is, isn't type nullability something that we need to tackle as part of solving this ticket anyway?

**Comment by eladb** [comment]
it’s a related topic but not the same. This issue is basically just a modeling improvement (move the “optional” indication from the type reference to the parameter/property specification). Nullability is a different attribute of type references which is not the same as optionality.

If at all, nullability should be part of the type-reference while optionality should be part of the consuming specification.
